# Generated by Django 5.1.2 on 2024-10-21 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("psy_faust", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="qualifications",
            options={
                "verbose_name": "Квалификации",
                "verbose_name_plural": "Квалификации",
            },
        ),
        migrations.AlterField(
            model_name="qualifications",
            name="img",
            field=models.ImageField(upload_to="", verbose_name="Картинка"),
        ),
        migrations.AlterField(
            model_name="qualifications",
            name="title",
            field=models.CharField(max_length=50, verbose_name="Название"),
        ),
    ]
