# Generated by Django 5.1.2 on 2024-10-21 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("psy_faust", "0004_faq"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="faq",
            options={"verbose_name": "FAQ", "verbose_name_plural": "FAQ"},
        ),
    ]
