# Generated by Django 5.1.2 on 2024-10-22 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("psy_faust", "0005_alter_faq_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contacts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("telegram", models.CharField(max_length=50, verbose_name="Telegram")),
                ("whatsapp", models.CharField(max_length=50, verbose_name="Whatsapp")),
                ("Email", models.CharField(max_length=50, verbose_name="EMail")),
                ("Phone", models.CharField(max_length=50, verbose_name="Телефон")),
            ],
            options={
                "verbose_name": "Контакт",
                "verbose_name_plural": "Контакты",
            },
        ),
    ]
