# Generated by Django 5.1.2 on 2024-10-22 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("psy_faust", "0006_contacts"),
    ]

    operations = [
        migrations.RenameField(
            model_name="contacts",
            old_name="Email",
            new_name="email",
        ),
        migrations.RenameField(
            model_name="contacts",
            old_name="Phone",
            new_name="phone",
        ),
    ]
