# Generated by Django 5.1.2 on 2025-01-14 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("psy_faust", "0008_alter_faq_title"),
    ]

    operations = [
        migrations.CreateModel(
            name="Services",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=22, verbose_name="Название услуги"),
                ),
                ("time", models.IntegerField(verbose_name="Продолжительность сессии")),
                (
                    "price",
                    models.IntegerField(max_length=5, verbose_name="Стоимость услуги"),
                ),
                ("desc", models.CharField(max_length=100, verbose_name="Описание")),
            ],
            options={
                "verbose_name": "Услуга",
                "verbose_name_plural": "Услуги",
            },
        ),
    ]
