# Generated by Django 5.1.2 on 2025-01-14 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("psy_faust", "0009_services"),
    ]

    operations = [
        migrations.AlterField(
            model_name="services",
            name="price",
            field=models.IntegerField(verbose_name="Стоимость услуги"),
        ),
        migrations.AlterField(
            model_name="services",
            name="time",
            field=models.IntegerField(verbose_name="Продолжительность сессии(минуты)"),
        ),
    ]
